apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-mysql-database
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabeles:
      app: user-service-mysql-database
  template:
    metadata:
      labels:
        app: user-service-mysql-database
    spec:
      containers:
        - name: user-service-mysql-database
          image: mysql:8
          ports: 
            - containerPort: 3306
          env: 
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-mysql-secret
                  key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: user-service-mysql-secret
                  key: mysql-database
          volumeMounts:
            - name: user-service-mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: user-service-mysql-data
          persistentVolumeClaim:
            claimName: user-service-mysql-pvc