apiVersion: v1
kind: Secret
metadata:
  name: user-service-mysql-secret
  namespace: development
type: Opaque
data: 
  mysql-user: cm9vdA==
  mysql-password: cm9vdDEyMw==
  mysql-database: dXNlcl9zZXJ2aWNl