apiVersion: v1
kind: PersistentVolume
metadata: 
  name: user-service-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
  claimRef: 
    name: user-service-mysql-pvc
    namespace: development